import type { Product, Category, User, Order, Review, BlogPost } from '@/types';

// Mock Products Data (200+ items as requested)
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Elegant Floral Summer Dress',
    slug: 'elegant-floral-summer-dress',
    description: 'A beautiful floral summer dress perfect for Rwanda\'s warm climate. Made from breathable cotton blend with a flattering A-line silhouette.',
    images: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&h=1000&fit=crop',
        alt: 'Elegant Floral Summer Dress',
        width: 800,
        height: 1000,
        isPrimary: true,
      },
      {
        id: '2',
        url: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&h=1000&fit=crop',
        alt: 'Elegant Floral Summer Dress Back View',
        width: 800,
        height: 1000,
        isPrimary: false,
      },
    ],
    variants: [
      {
        id: '1-s',
        sku: 'EFS-001-S-PINK',
        price: 35000,
        salePrice: 28000,
        size: 'S',
        color: 'Pink Floral',
        stock: 15,
        isAvailable: true,
      },
      {
        id: '1-m',
        sku: 'EFS-001-M-PINK',
        price: 35000,
        salePrice: 28000,
        size: 'M',
        color: 'Pink Floral',
        stock: 20,
        isAvailable: true,
      },
      {
        id: '1-l',
        sku: 'EFS-001-L-PINK',
        price: 35000,
        salePrice: 28000,
        size: 'L',
        color: 'Pink Floral',
        stock: 12,
        isAvailable: true,
      },
    ],
    tags: ['dress', 'summer', 'floral', 'casual', 'new-arrival'],
    categoryId: 'dresses',
    weight: 300,
    vendor: 'H for Her',
    originCountry: 'China',
    shippingEligible: true,
    rating: 4.8,
    reviewCount: 47,
    isFeatured: true,
    isNew: true,
    isTrending: true,
    createdAt: '2024-10-01T10:00:00Z',
    updatedAt: '2024-10-14T15:30:00Z',
  },
  {
    id: '2',
    name: 'Professional Blazer - Office Chic',
    slug: 'professional-blazer-office-chic',
    description: 'A sophisticated blazer designed for the modern working woman. Features a tailored fit and premium fabric blend.',
    images: [
      {
        id: '3',
        url: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
        alt: 'Professional Blazer',
        width: 800,
        height: 1000,
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: '2-s',
        sku: 'PB-002-S-BLACK',
        price: 45000,
        size: 'S',
        color: 'Black',
        stock: 8,
        isAvailable: true,
      },
      {
        id: '2-m',
        sku: 'PB-002-M-BLACK',
        price: 45000,
        size: 'M',
        color: 'Black',
        stock: 12,
        isAvailable: true,
      },
      {
        id: '2-l',
        sku: 'PB-002-L-BLACK',
        price: 45000,
        size: 'L',
        color: 'Black',
        stock: 6,
        isAvailable: true,
      },
    ],
    tags: ['blazer', 'professional', 'office', 'formal', 'work-wear'],
    categoryId: 'work-wear',
    weight: 500,
    vendor: 'H for Her',
    originCountry: 'China',
    shippingEligible: true,
    rating: 4.6,
    reviewCount: 23,
    isFeatured: true,
    isNew: false,
    isTrending: false,
    createdAt: '2024-09-15T08:00:00Z',
    updatedAt: '2024-10-10T12:15:00Z',
  },
  // ... Continue with more products to reach 200+
  // For brevity, I'll add a few more examples and note that this would continue
];

// Generate additional mock products programmatically to reach 200+
const productTemplates = [
  {
    name: 'Casual T-Shirt',
    category: 'casual',
    basePrice: 15000,
    tags: ['t-shirt', 'casual', 'everyday'],
  },
  {
    name: 'Denim Jeans',
    category: 'bottoms',
    basePrice: 40000,
    tags: ['jeans', 'denim', 'casual'],
  },
  {
    name: 'Evening Gown',
    category: 'dresses',
    basePrice: 65000,
    tags: ['gown', 'evening', 'formal'],
  },
  {
    name: 'Leather Handbag',
    category: 'accessories',
    basePrice: 35000,
    tags: ['bag', 'handbag', 'accessories'],
  },
  {
    name: 'Silk Scarf',
    category: 'accessories',
    basePrice: 12000,
    tags: ['scarf', 'silk', 'accessories'],
  },
];

// Generate additional products
for (let i = 3; i <= 200; i++) {
  const template = productTemplates[i % productTemplates.length];
  const isOnSale = Math.random() > 0.7;
  const salePrice = isOnSale ? Math.floor(template.basePrice * 0.8) : undefined;
  
  mockProducts.push({
    id: i.toString(),
    name: `${template.name} ${i}`,
    slug: `${template.name.toLowerCase().replace(/\s+/g, '-')}-${i}`,
    description: `High-quality ${template.name.toLowerCase()} imported from China. Perfect for modern Rwandan women.`,
    images: [
      {
        id: `${i}-1`,
        url: `https://picsum.photos/800/1000?random=${i}`,
        alt: `${template.name} ${i}`,
        width: 800,
        height: 1000,
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: `${i}-s`,
        sku: `${template.name.toUpperCase().replace(/\s+/g, '')}-${i}-S`,
        price: template.basePrice,
        salePrice,
        size: 'S',
        color: 'Default',
        stock: Math.floor(Math.random() * 20) + 5,
        isAvailable: true,
      },
      {
        id: `${i}-m`,
        sku: `${template.name.toUpperCase().replace(/\s+/g, '')}-${i}-M`,
        price: template.basePrice,
        salePrice,
        size: 'M',
        color: 'Default',
        stock: Math.floor(Math.random() * 20) + 5,
        isAvailable: true,
      },
    ],
    tags: template.tags,
    categoryId: template.category,
    weight: Math.floor(Math.random() * 500) + 200,
    vendor: 'H for Her',
    originCountry: 'China',
    shippingEligible: true,
    rating: parseFloat((3.5 + Math.random() * 1.5).toFixed(1)),
    reviewCount: Math.floor(Math.random() * 100),
    isFeatured: Math.random() > 0.8,
    isNew: Math.random() > 0.7,
    isTrending: Math.random() > 0.8,
    createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  });
}

export const mockCategories: Category[] = [
  {
    id: 'new-arrivals',
    name: 'New Arrivals',
    slug: 'new-arrivals',
    description: 'Latest fashion trends from China',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=600&fit=crop',
    isActive: true,
    sortOrder: 1,
    productCount: 45,
  },
  {
    id: 'dresses',
    name: 'Dresses',
    slug: 'dresses',
    description: 'Beautiful dresses for every occasion',
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&h=600&fit=crop',
    isActive: true,
    sortOrder: 2,
    productCount: 67,
  },
  {
    id: 'work-wear',
    name: 'Work Wear',
    slug: 'work-wear',
    description: 'Professional attire for the modern woman',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&h=600&fit=crop',
    isActive: true,
    sortOrder: 3,
    productCount: 34,
  },
  {
    id: 'casual',
    name: 'Casual',
    slug: 'casual',
    description: 'Comfortable everyday fashion',
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&h=600&fit=crop',
    isActive: true,
    sortOrder: 4,
    productCount: 89,
  },
  {
    id: 'accessories',
    name: 'Accessories',
    slug: 'accessories',
    description: 'Complete your perfect look',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=600&fit=crop',
    isActive: true,
    sortOrder: 5,
    productCount: 52,
  },
];

export const mockUser: User = {
  id: '1',
  name: 'Grace Uwimana',
  email: 'grace@example.com',
  phone: '+250788123456',
  avatar: 'https://images.unsplash.com/photo-1494790108755-2616c0763a86?w=150&h=150&fit=crop',
  addresses: [
    {
      id: '1',
      type: 'shipping',
      firstName: 'Grace',
      lastName: 'Uwimana',
      address1: 'KG 15 Ave',
      address2: 'Kimisagara',
      city: 'Kigali',
      province: 'Kigali',
      country: 'Rwanda',
      phone: '+250788123456',
      isDefault: true,
    },
  ],
  role: 'customer',
  savedSizes: [
    { category: 'dresses', size: 'M' },
    { category: 'tops', size: 'S' },
  ],
  wishlist: ['1', '3', '7'],
  preferences: {
    language: 'en',
    currency: 'RWF',
    notifications: {
      email: true,
      sms: true,
      push: false,
    },
  },
  createdAt: '2024-01-15T10:00:00Z',
  updatedAt: '2024-10-14T15:30:00Z',
};

export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Summer Fashion Trends from China: What\'s Hot in Rwanda',
    slug: 'summer-fashion-trends-china-rwanda',
    excerpt: 'Discover the latest summer fashion trends making their way from China to Rwanda\'s fashion scene.',
    content: 'Full blog content would go here...',
    featuredImage: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=600&fit=crop',
    tags: ['fashion', 'trends', 'summer', 'china'],
    author: {
      name: 'Marie Claire',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    },
    isPublished: true,
    publishedAt: '2024-10-10T09:00:00Z',
    createdAt: '2024-10-08T14:00:00Z',
    seo: {
      title: 'Summer Fashion Trends from China: What\'s Hot in Rwanda | H for Her',
      description: 'Discover the latest summer fashion trends making their way from China to Rwanda\'s fashion scene.',
      keywords: ['fashion trends', 'summer fashion', 'China fashion', 'Rwanda style'],
    },
  },
  {
    id: '2',
    title: 'How to Style Your Work Wardrobe: Professional Tips',
    slug: 'style-work-wardrobe-professional-tips',
    excerpt: 'Expert tips on building a professional wardrobe that reflects your personal style.',
    content: 'Full blog content would go here...',
    featuredImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&h=600&fit=crop',
    tags: ['workwear', 'professional', 'styling', 'tips'],
    author: {
      name: 'Ange Mukamana',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    },
    isPublished: true,
    publishedAt: '2024-10-12T11:00:00Z',
    createdAt: '2024-10-10T16:00:00Z',
  },
];
